name: Happinest
description: A new Flutter project.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  provider: ^6.0.5
#  http:

  flutter_dotenv: any
  google_fonts:
  flutter_screenutil: ^5.9.0
  flutter_riverpod: ^2.4.5

  # To initialize Firebase:
  firebase_core: ^2.7.0

  # To use Firebase Authentication(Google & Apple):
  firebase_auth:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Google sign in:
  google_sign_in:

  # Apple sign in:
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.2

  # Handle Notification via FCM:
  firebase_messaging: 14.2.1 #^14.2.5
#  flutter_login_facebook:

  audioplayers: ^5.2.1

  shared_preferences: ^2.3.2
  permission_handler: ^11.1.0
  location: ^5.0.3
  latlong2: ^0.8.1
  geolocator: ^10.1.0
  flutter_easyloading: ^3.0.5
#  colorful_safe_area: ^1.0.0
  image_picker: ^1.0.5
#  image_cropper:
  shimmer: ^3.0.0
  flutter_initicon: ^3.0.0+1
  file_picker:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bounce: ^1.1.0
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.3.9
  fluttertoast: ^8.2.4
  connectivity_plus: ^6.1.3
  device_info_plus:
  intl:
  cached_network_image: ^3.4.1
  geocoding: ^2.1.1
#  geocode: ^1.0.3
  google_maps_flutter: ^2.5.0
  flutter_contacts: ^1.1.7+1
  photo_manager:
    path: flutter_photo_manager-main
  url_launcher: ^6.2.1
#  share_plus: ^9.0.0
  dio: ^5.4.0
  requests_inspector: ^4.2.1
  fpdart: ^1.1.0
  flutter_expandable_fab: ^2.0.0
  card_swiper: ^3.0.1
#  native_exif:
  pull_to_refresh: ^2.0.0
  path_provider: ^2.1.5
#  uni_links: ^0.5.1
  system_date_time_format: ^0.7.0
  flutter_image_compress: ^2.1.0
  crop_image: ^1.0.12
  video_player: ^2.8.2
  webview_flutter: ^4.7.0
  flutter_pdfview: ^1.3.2
  flutter_html: ^3.0.0-beta.2
#  exif: ^3.3.0
  flutter_local_notifications: ^17.1.1
  share_plus: ^10.1.4
  package_info_plus: ^8.1.4
#  social_share: ^2.3.1
#  assets_audio_player: ^3.1.1
  google_places_flutter: ^2.0.7
  gallery_saver_plus: ^3.2.1

  riverpod: any
  permission_handler_platform_interface: any


dev_dependencies:
  flutter_test:
    sdk: flutter
#  build_runner: ^2.2.0
#  mobx_codegen: ^2.0.7
  flutter_lints: ^3.0.1

dependency_overrides:
  graphql_flutter: ^5.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/png_icons/
    - assets/gifs/
    - assets/.env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
